apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-controller
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: db-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: db-controller
    spec:
      containers:
      - command:
        - /manager
        image: ghcr.io/doodlescheduling/db-controller:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        name: manager
        ports:
          - containerPort: 9557
            name: healthz
            protocol: TCP
          - containerPort: 9556
            name: metrics
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
