apiVersion: v2
appVersion: 0.0.0
description: A kubernetes controller to deploy databases
home: https://github.com/DoodleScheduling/kubedb
keywords:
- kubernetes-controller
- mongodb
- postgresql
- vault
name: kubedb
sources:
- https://github.com/DoodleScheduling/kubedb
version: 0.0.0
