# permissions for end users to edit mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbdatabase-editor-role
rules:
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbdatabases/status
  verbs:
  - get
