# permissions for end users to view mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbuser-viewer-role
rules:
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbusers/status
  verbs:
  - get
