# permissions for end users to view mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-viewer-role
rules:
- apiGroups:
  - infra.doodle.com
  resources:
  - mongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.doodle.com
  resources:
  - mongodbs/status
  verbs:
  - get
