# permissions for end users to view mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbdatabase-viewer-role
rules:
- apiGroups:
  - infra.doodle.com
  resources:
  - mongodbdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.doodle.com
  resources:
  - mongodbdatabases/status
  verbs:
  - get
