# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqluser-viewer-role
rules:
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqlusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqlusers/status
  verbs:
  - get
