# permissions for end users to edit postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqldatabase-editor-role
rules:
- apiGroups:
  - infra.doodle.com
  resources:
  - postgresqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.doodle.com
  resources:
  - postgresqldatabases/status
  verbs:
  - get
