# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqldatabase-viewer-role
rules:
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqldatabases/status
  verbs:
  - get
