# permissions for end users to edit postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqluser-editor-role
rules:
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - postgresqlusers/status
  verbs:
  - get
