---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbdatabases
  - mongodbusers
  - postgresqldatabases
  - postgresqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbprovisioning.infra.doodle.com
  resources:
  - mongodbdatabases/status
  - mongodbusers/status
  - postgresqldatabases/status
  - postgresqlusers/status
  verbs:
  - get
  - patch
  - update
