apiVersion: dbprovisioning.infra.doodle.com/v1beta1
kind: MongoDBDatabase
metadata:
  name: my-app
  namespace: default
spec:
  address: "mongodb://localhost:27017"
  rootSecret:
    name: mongodb
    passwordField: "mongodb-root-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: default
data:
  mongodb-root-password: MTIzNA==
  username: MTIzNA==
