apiVersion: infra.doodle.com/v1beta1
kind: PostgreSQL
metadata:
  name: postgresql-sample
  namespace: devops
spec:
  databaseName: "postgres_sample"
  hostName: "postgres-postgresql.devops:5432"
  rootUsername: postgres
  rootSecretLookup:
    name: postgres-postgresql
    namespace: devops
    field: postgresql-password
  credentials:
  - username: keycloak
    vault:
      useAvailable: true
      host: vault.devops
      path: secret/doodle/devbox/keycloak/database
      userField: USERNAME
      secretField: PASSWORD
  - username: replication
    vault:
      useAvailable: true
      host: vault.devops
      path: secret/doodle/devbox/keycloak/database
      userField: USERNAME
      secretField: PASSWORD
