apiVersion: infra.doodle.com/v1beta1
kind: PostgreSQLDatabase
metadata:
  name: postgresqldatabase-sample
  namespace: devops
spec:
  databaseName: "postgres_sample"
  hostName: "postgres-postgresql.devops:5432"
  rootUsername: postgres
  rootSecretLookup:
    name: postgres-postgresql
    namespace: devops
    field: postgresql-password
  credentials:
  - username: keycloak
    vault:
      useAvailable: true
      host: "https://vault.devops:8200"
      path: secret/doodle/devbox/keycloak/database
      userField: USERNAME
      secretField: PASSWORD
  - username: replication
    vault:
      useAvailable: true
      host: "https://vault.devops:8200"
      path: secret/doodle/devbox/keycloak/replication
      userField: USERNAME
      secretField: PASSWORD
  - username: mirror
    vault:
      useAvailable: true
      host: "https://vault.devops:8200"
      path: secret/doodle/devbox/keycloak/mirror
      userField: USERNAME
      secretField: PASSWORD
