apiVersion: infra.doodle.com/v1beta1
kind: MongoDB
metadata:
  name: mongodb-sample
  namespace: devops
spec:
  databaseName: "mongodb_sample"
  hostName: "mongodb.devops:27017"
  rootUsername: root
  rootAuthDatabase: admin
  rootSecretLookup:
    name: mongodb
    namespace: devops
    field: mongodb-root-password
  credentials:
  - username: admin
    vault:
      useAvailable: true
      host: vault.devops
      path: secret/doodle/devbox/monolith
      userField: USERNAME
      secretField: PASSWORD
