apiVersion: dbprovisioning.infra.doodle.com/v1beta1
kind: MongoDBUser
metadata:
  name: my-app
  namespace: default
spec:
  database:
    name: my-app
  credentials:
    name: my-app-mongodb
  roles:
  - db: my-app
    role: readWrite
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-mongodb
  namespace: default
data:
  password: MTIzNA==
  username: MTIzNA==
