apiVersion: dbprovisioning.infra.doodle.com/v1beta1
kind: PostgreSQLDatabase
metadata:
  name: my-app
  namespace: default
spec:
  address: "postgres://localhost:5432"
  rootSecret:
    name: postgresql
    passwordField: "postgresql-password"
  extensions:
    - name: pg_trgm
---
apiVersion: dbprovisioning.infra.doodle.com/v1beta1
kind: PostgreSQLUser
metadata:
  name: my-app
  namespace: default
spec:
  database:
    name: my-app
  credentials:
    name: my-app-postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-postgresql
  namespace: default
data:
  password: MTIzNA==
  username: MTIzNA==
