apiVersion: dbprovisioning.infra.doodle.com/v1beta1
kind: PostgreSQLDatabase
metadata:
  name: my-app
  namespace: default
spec:
  address: "postgres://localhost:5432"
  rootSecret:
    name: postgresql
    passwordField: "postgresql-password"
  extensions:
  - name: pg_trgm
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: default
data:
  postgresql-password: MTIzNA==
  username: MTIzNA==
