apiVersion: v2
appVersion: 0.0.0
description: A kubernetes controller to deploy databases
home: https://github.com/DoodleScheduling/k8sdb-controller
keywords:
- kubernetes-controller
- mongodb
- postgresql
name: k8sdb-controller
sources:
- https://github.com/DoodleScheduling/k8sdb-controller
version: 0.0.0
