{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "db-controller.fullname" . }}-edit
  labels:
    app.kubernetes.io/name: {{ include "db-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "db-controller.chart" . }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "dbprovisioning.infra.doodle.com"
  resources:
  - mongodbdatabases
  - mongodbusers
  - postgresqldatabases
  - postgresqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "dbprovisioning.infra.doodle.com"
  resources:
  - mongodbdatabases/status
  - mongodbusers/status
  - postgresqldatabases/status
  - postgresqlusers/status
  verbs:
  - get
{{- end }}
