{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubedb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubedb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "kubedb.chart" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
    - "secrets"
  verbs:
    - get
    - list
    - watch
    - update
- apiGroups:
  - "infra.doodle.com"
  resources:
  - mongodbdatabases
  - postgresqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "infra.doodle.com"
  resources:
  - mongodbdatabases/status
  - postgresqldatabases/status
  verbs:
  - get
  - patch
  - update
{{- end }}
