name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Setup envtest
        uses: fluxcd/pkg/actions/envtest@main
        with:
          version: "1.19.2"
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
      - name: Run tests
        uses: ./.github/actions/run-tests
        env:
          GOPATH: /github/home/go
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build container image
        run: make docker-build IMG=test/k8sdb-controller TAG=latest BUILD_PLATFORMS=linux/amd64 BUILD_ARGS=--load
      - name: Load test image
        run: kind load docker-image test/k8sdb-controller:latest
      - name: Deploy controller
        run: make dev-deploy IMG=test/k8sdb-controller TAG=latest
      - name: Setup MongoDB
        env:
          MONGODB_VER: ${{ '10.29.2' }}
        run: |
          kubectl create ns mongodb
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --wait -i mongodb bitnami/mongodb \
          --version $MONGOBD_VER \
          --namespace mongodb \
          --set auth.rootPassword=password \
          --set persistence.enabled=false
          kubectl -n ctrl-system apply -f ./config/testdata/mongodb/secret.yaml
          dpkg -i https://github.com//mongodb/mongocli/releases/download/v1.20.4/mongocli_1.20.4_linux_x86_64.deb
          kubectl port-forward svc/mongodb 27017 &
          sleep 2
      - name: Run MongoDB tests
        run: |
          kubectl -n ctrl-system apply -f ./config/testdata/mongodbdatabase
          kubectl -n ctrl-system apply -f ./config/testdata/mongodbuser
          kubectl -n ctrl-system wait mongodbdatabase/foo --for=condition=ready --timeout=1m
          kubectl -n ctrl-system wait mongodbuser/foo --for=condition=ready --timeout=1m
          mongo mongodb://localhost:27017/foo --authDatabase=admin -u foo -p password --eval 'db.bar.insertInto({"foo":"bar"})'
      - name: Logs
        run: |
          kubectl -n ctrl-system logs deploy/k8sdb-controller
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n kube-system describe pods
          kubectl -n ctrl-system describe pods
          kubectl -n ctrl-system get mongodbdatabase -oyaml
          kubectl -n ctrl-system get mongodbuser -oyaml
          kubectl -n ctrl-system get postgresqldatabase -oyaml
          kubectl -n ctrl-system get postgresqluser -oyaml
          kubectl -n ctrl-system get all
          kubectl -n ctrl-system logs deploy/k8sdb-controller
          kubectl -n minio get all
