name: pr-gorelaser

permissions: {}

on:
  pull_request:
    branches:
      - 'master'

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate .goreleaser.yaml
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: latest
          args: check
        env:
          RUNNER_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.DOODLE_OSS_BOT}}
